#!/usr/bin/env python

from bs4 import BeautifulSoup
import requests

r = requests.get('https://www.biblegateway.com/passage/?search=Psalm+4&version=NIV&interface=print')
soup = BeautifulSoup(r.text)
print soup.find(class_="result-text-style-normal").text
