#!/usr/bin/env python3

from bs4 import BeautifulSoup
import requests

r = requests.get('https://www.biblegateway.com/passage/?search=Psalm+4&version=NIV')
soup = BeautifulSoup(r.text,  "html.parser")
print(soup.find(class_="result-text-style-normal").text)
