#!/usr/bin/env python

from bs4 import BeautifulSoup
import urllib

r = urllib.urlopen('https://www.biblegateway.com/passage/?search=John+3%3A16&version=NIV').read()
soup = BeautifulSoup(r)
print soup.find(class_="result-text-style-normal").text
